export type DiceMaterial = 'none' | 'plastic' | 'glass' | 'metal' | 'wood'

export const MATERIALS: readonly DiceMaterial[] = [
  'none',
  'plastic',
  'glass',
  'metal',
  'wood',
] as const

export type ColorsetPreset = {
  /** Lookup key passed to dice-box-threejs as `theme_colorset`. */
  key: string
  name: string
  category: string
  /** A representative face colour for swatches (the lib's actual rendering may vary by texture). */
  foreground: string
  background: string
}

export const DEFAULT_COLORSET = 'white'
export const DEFAULT_MATERIAL: DiceMaterial = 'glass'

export const COLORSETS: readonly ColorsetPreset[] = [
  {
    key: 'black',
    name: 'Black',
    category: 'Colors',
    foreground: '#ffffff',
    background: '#000000',
  },
  {
    key: 'rainbow',
    name: 'Rainblow',
    category: 'Colors',
    foreground: '#FF5959',
    background: '#900000',
  },
  {
    key: 'test',
    name: 'Test',
    category: 'Colors',
    foreground: '#00FF00',
    background: '#FF0000',
  },
  {
    key: 'white',
    name: 'White',
    category: 'Colors',
    foreground: '#000000',
    background: '#FFFFFF',
  },
  {
    key: 'astralsea',
    name: 'Astral Sea',
    category: 'Custom Sets',
    foreground: '#565656',
    background: '#ffffff',
  },
  {
    key: 'birdup',
    name: 'Bird Up',
    category: 'Custom Sets',
    foreground: '#FFFFFF',
    background: '#F11602',
  },
  {
    key: 'bloodmoon',
    name: 'Blood Moon',
    category: 'Custom Sets',
    foreground: '#CDB800',
    background: '#6F0000',
  },
  {
    key: 'glitterparty',
    name: 'Glitter Party',
    category: 'Custom Sets',
    foreground: '#ffffff',
    background: '#FFB5F5',
  },
  {
    key: 'dragons',
    name: 'Here be Dragons',
    category: 'Custom Sets',
    foreground: '#FFFFFF',
    background: '#B80000',
  },
  {
    key: 'inspired',
    name: 'Inspired',
    category: 'Custom Sets',
    foreground: '#FFD800',
    background: '#C4C4B6',
  },
  {
    key: 'breebaby',
    name: 'Pastel Sunset',
    category: 'Custom Sets',
    foreground: '#5E175E',
    background: '#FE89CF',
  },
  {
    key: 'pinkdreams',
    name: 'Pink Dreams',
    category: 'Custom Sets',
    foreground: '#ffffff',
    background: '#ff007c',
  },
  {
    key: 'starynight',
    name: 'Stary Night',
    category: 'Custom Sets',
    foreground: '#4F708F',
    background: '#091636',
  },
  {
    key: 'bronze',
    name: 'Thylean Bronze',
    category: 'Custom Sets',
    foreground: '#FF9159',
    background: '#705206',
  },
  {
    key: 'acid',
    name: 'Acid',
    category: 'Damage Types',
    foreground: '#A9FF70',
    background: '#a6ff00',
  },
  {
    key: 'air',
    name: 'Air',
    category: 'Damage Types',
    foreground: '#ffffff',
    background: '#d0e5ea',
  },
  {
    key: 'earth',
    name: 'Earth',
    category: 'Damage Types',
    foreground: '#6C9943',
    background: '#346804',
  },
  {
    key: 'fire',
    name: 'Fire',
    category: 'Damage Types',
    foreground: '#f8d84f',
    background: '#f43c04',
  },
  {
    key: 'force',
    name: 'Force',
    category: 'Damage Types',
    foreground: '#ffffff',
    background: '#FF97FF',
  },
  {
    key: 'ice',
    name: 'Ice',
    category: 'Damage Types',
    foreground: '#60E9FF',
    background: '#214fa3',
  },
  {
    key: 'lightning',
    name: 'Lightning',
    category: 'Damage Types',
    foreground: '#FFC500',
    background: '#f17105',
  },
  {
    key: 'necrotic',
    name: 'Necrotic',
    category: 'Damage Types',
    foreground: '#ffffff',
    background: '#6F0000',
  },
  {
    key: 'poison',
    name: 'Poison',
    category: 'Damage Types',
    foreground: '#D6A8FF',
    background: '#313866',
  },
  {
    key: 'psychic',
    name: 'Psychic',
    category: 'Damage Types',
    foreground: '#D6A8FF',
    background: '#313866',
  },
  {
    key: 'radiant',
    name: 'Radiant',
    category: 'Damage Types',
    foreground: '#F9B333',
    background: '#FFFFFF',
  },
  {
    key: 'thunder',
    name: 'Thunder',
    category: 'Damage Types',
    foreground: '#FFC500',
    background: '#7D7D7D',
  },
  {
    key: 'water',
    name: 'Water',
    category: 'Damage Types',
    foreground: '#60E9FF',
    background: '#87b8c4',
  },
  {
    key: 'acleaf',
    name: 'Animal Crossing',
    category: 'Other',
    foreground: '#00FF00',
    background: '#07540A',
  },
  {
    key: 'covid',
    name: 'COViD',
    category: 'Other',
    foreground: '#A9FF70',
    background: '#a6ff00',
  },
  {
    key: 'coin_default',
    name: 'Gold Coin',
    category: 'Other',
    foreground: '#1c1100',
    background: '#f6c928',
  },
  {
    key: 'isabelle',
    name: 'Isabelle',
    category: 'Other',
    foreground: '#000000',
    background: '#FEE5CC',
  },
  {
    key: 'thecage',
    name: 'Nicholas Cage',
    category: 'Other',
    foreground: '#000000',
    background: '#ffffff',
  },
  {
    key: 'coin_silver',
    name: 'Silver Coin',
    category: 'Other',
    foreground: '#1c1100',
    background: '#cccccc',
  },
  {
    key: 'tigerking',
    name: 'Tiger King',
    category: 'Other',
    foreground: '#000000',
    background: '#FFCC40',
  },
  {
    key: 'swa_black',
    name: 'Armada Attack - Black',
    category: 'Star Wars™ Armada',
    foreground: '#ffffff',
    background: '#252223',
  },
  {
    key: 'swa_blue',
    name: 'Armada Attack - Blue',
    category: 'Star Wars™ Armada',
    foreground: '#ffffff',
    background: '#212642',
  },
  {
    key: 'swa_red',
    name: 'Armada Attack - Red',
    category: 'Star Wars™ Armada',
    foreground: '#ffffff',
    background: '#440D19',
  },
  {
    key: 'swl_atkblack',
    name: 'Legion Attack - Black',
    category: 'Star Wars™ Legion',
    foreground: '#ffffff',
    background: '#252223',
  },
  {
    key: 'swl_atkred',
    name: 'Legion Attack - Red',
    category: 'Star Wars™ Legion',
    foreground: '#ffffff',
    background: '#440D19',
  },
  {
    key: 'swl_atkwhite',
    name: 'Legion Attack - White',
    category: 'Star Wars™ Legion',
    foreground: '#000000',
    background: '#ffffff',
  },
  {
    key: 'swl_defred',
    name: 'Legion Defense - Red',
    category: 'Star Wars™ Legion',
    foreground: '#ffffff',
    background: '#440D19',
  },
  {
    key: 'swl_defwhite',
    name: 'Legion Defense - White',
    category: 'Star Wars™ Legion',
    foreground: '#000000',
    background: '#ffffff',
  },
  {
    key: 'swrpg_abi',
    name: 'Star Wars RPG - Ability',
    category: 'Star Wars™ RPG',
    foreground: '#00FF00',
    background: '#3D9238',
  },
  {
    key: 'swrpg_boo',
    name: 'Star Wars RPG - Boost',
    category: 'Star Wars™ RPG',
    foreground: '#00FFFF',
    background: '#4B9DC6',
  },
  {
    key: 'swrpg_cha',
    name: 'Star Wars RPG - Challenge',
    category: 'Star Wars™ RPG',
    foreground: '#FF0000',
    background: '#A91F32',
  },
  {
    key: 'swrpg_dif',
    name: 'Star Wars RPG - Difficulty',
    category: 'Star Wars™ RPG',
    foreground: '#8000FC',
    background: '#39165F',
  },
  {
    key: 'swrpg_for',
    name: 'Star Wars RPG - Force',
    category: 'Star Wars™ RPG',
    foreground: '#000000',
    background: '#F3F3F3',
  },
  {
    key: 'swrpg_pro',
    name: 'Star Wars RPG - Proficiency',
    category: 'Star Wars™ RPG',
    foreground: '#FFFF00',
    background: '#CABB1C',
  },
  {
    key: 'swrpg_set',
    name: 'Star Wars RPG - Setback',
    category: 'Star Wars™ RPG',
    foreground: '#ffffff',
    background: '#252223',
  },
  {
    key: 'xwing_green',
    name: 'X-Wing Attack - Green',
    category: 'Star Wars™ X-Wing',
    foreground: '#ffffff',
    background: '#3D9238',
  },
  {
    key: 'xwing_red',
    name: 'X-Wing Attack - Red',
    category: 'Star Wars™ X-Wing',
    foreground: '#ffffff',
    background: '#440D19',
  },
]

export const findColorset = (key: string): ColorsetPreset | undefined =>
  COLORSETS.find(c => c.key === key)
